use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::str::FromStr;

/// Impact severity level of an economic event.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Impact {
    #[serde(rename = "Non-Economic", alias = "None", alias = "Holiday")]
    NonEconomic,
    #[serde(rename = "Low", alias = "low")]
    Low,
    #[serde(rename = "Medium", alias = "medium", alias = "Med")]
    Medium,
    #[serde(rename = "High", alias = "high", alias = "Red")]
    High,
    #[serde(untagged)]
    Custom(String),
}

impl Impact {
    pub fn is_high(&self) -> bool {
        matches!(self, Impact::High)
    }

    pub fn is_red_folder(&self) -> bool {
        self.is_high()
    }

    pub fn matches_str(&self, text: &str) -> bool {
        match self {
            Impact::High => text.eq_ignore_ascii_case("High") || text.eq_ignore_ascii_case("Red"),
            Impact::Medium => {
                text.eq_ignore_ascii_case("Medium") || text.eq_ignore_ascii_case("Med")
            }
            Impact::Low => text.eq_ignore_ascii_case("Low"),
            Impact::NonEconomic => {
                text.eq_ignore_ascii_case("Non-Economic")
                    || text.eq_ignore_ascii_case("None")
                    || text.eq_ignore_ascii_case("Holiday")
            }
            Impact::Custom(s) => s.eq_ignore_ascii_case(text),
        }
    }
}

impl fmt::Display for Impact {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Impact::High => write!(f, "High"),
            Impact::Medium => write!(f, "Medium"),
            Impact::Low => write!(f, "Low"),
            Impact::NonEconomic => write!(f, "Non-Economic"),
            Impact::Custom(s) => write!(f, "{}", s),
        }
    }
}

impl FromStr for Impact {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(match s.trim().to_lowercase().as_str() {
            "high" | "red" => Impact::High,
            "medium" | "med" => Impact::Medium,
            "low" => Impact::Low,
            "non-economic" | "none" | "holiday" => Impact::NonEconomic,
            other => Impact::Custom(other.to_string()),
        })
    }
}

/// A parsed economic calendar event from the calendar feed.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct EconomicEvent {
    pub title: String,
    pub country: String,
    pub impact: String,
    pub datetime: DateTime<Utc>,
}

/// Backwards compatibility alias for `EconomicEvent`.
pub type NewsEvent = EconomicEvent;

/// An individual event recorded within a merged blackout window.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct WindowEvent {
    /// True if generated by a weekend curfew or custom rule rather than external calendar API.
    pub is_custom: bool,
    pub event_time: DateTime<Utc>,
    pub country: String,
    pub impact: String,
    pub title: String,
}

/// A merged blackout window containing one or more events.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BlackoutWindow {
    pub start: DateTime<Utc>,
    pub end: DateTime<Utc>,
    pub events: Vec<WindowEvent>,
}

impl BlackoutWindow {
    /// Returns the minutes remaining until this blackout window ends.
    /// If the window has already passed, returns 0.
    pub fn remaining_minutes(&self) -> i64 {
        (self.end - Utc::now()).num_seconds().max(0) / 60
    }

    /// Total duration of the window in minutes.
    pub fn duration_minutes(&self) -> i64 {
        (self.end - self.start).num_seconds() / 60
    }

    /// Whether this window is currently active at the specified timestamp.
    pub fn is_active_at(&self, time: DateTime<Utc>) -> bool {
        self.start <= time && time <= self.end
    }

    /// Whether this window is currently active right now.
    pub fn is_active(&self) -> bool {
        self.is_active_at(Utc::now())
    }

    /// Primary event title in this window (or summary if multiple).
    pub fn summary_title(&self) -> String {
        if self.events.is_empty() {
            "Blackout Window".to_string()
        } else if self.events.len() == 1 {
            self.events[0].title.clone()
        } else {
            format!("{} (+{} events)", self.events[0].title, self.events.len() - 1)
        }
    }
}

/// Event sent to workers or subscribers when blackout status changes.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct BlackoutNotification {
    pub active: bool,
    pub window: Option<BlackoutWindow>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Duration;

    #[test]
    fn test_impact_parsing_and_matching() {
        assert_eq!("High".parse::<Impact>().unwrap(), Impact::High);
        assert_eq!("red".parse::<Impact>().unwrap(), Impact::High);
        assert_eq!("Medium".parse::<Impact>().unwrap(), Impact::Medium);
        assert_eq!("low".parse::<Impact>().unwrap(), Impact::Low);

        let high = Impact::High;
        assert!(high.is_high());
        assert!(high.matches_str("high"));
        assert!(high.matches_str("red"));
        assert!(!high.matches_str("medium"));
    }

    #[test]
    fn test_blackout_window_methods() {
        let now = Utc::now();
        let window = BlackoutWindow {
            start: now - Duration::minutes(10),
            end: now + Duration::minutes(20),
            events: vec![WindowEvent {
                is_custom: false,
                event_time: now,
                country: "USD".to_string(),
                impact: "High".to_string(),
                title: "US CPI Release".to_string(),
            }],
        };

        assert!(window.is_active());
        assert_eq!(window.duration_minutes(), 30);
        assert!(window.remaining_minutes() >= 19 && window.remaining_minutes() <= 20);
        assert_eq!(window.summary_title(), "US CPI Release");
    }
}
